<?php
/**
 * Theme supports and text domain.
 *
 * @package Basecoat
 */

/**
 * Load the theme text domain.
 *
 * Translations live in `languages/`, generated by `bin/harness pot`.
 *
 * @return void
 */
function basecoat_load_textdomain() {
	load_theme_textdomain( 'basecoat', get_stylesheet_directory() . '/languages' );
}
add_action( 'after_setup_theme', 'basecoat_load_textdomain' );
